#############################################################################
# Makefile for building: build_bin/paint
# Generated by qmake (1.07a) (Qt 3.3.6) on: Fri Mar  8 22:55:23 2013
# Project:  paint.pro
# Template: app
# Command: $(QMAKE) -o Makefile paint.pro
#############################################################################

####### Compiler, tools and options

CC       = gcc
CXX      = g++
LEX      = flex
YACC     = yacc
CFLAGS   = -pipe -Wall -W -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic  -DQT_NO_DEBUG -DQT_SHARED -DQT_THREAD_SUPPORT
CXXFLAGS = -pipe -Wall -W -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic  -DQT_NO_DEBUG -DQT_SHARED -DQT_THREAD_SUPPORT
LEXFLAGS = 
YACCFLAGS= -d
INCPATH  = -I/usr/lib64/qt-3.3/mkspecs/linux-g++-64 -I. -Iinclude -I$(QTDIR)/include -Ibuild_tmp/
LINK     = g++
LFLAGS   = 
LIBS     = $(SUBLIBS) -L$(QTDIR)/lib -lqt-mt -lXext -lX11 -lm
AR       = ar cqs
RANLIB   = 
MOC      = $(QTDIR)/bin/moc
UIC      = $(QTDIR)/bin/uic
QMAKE    = qmake
TAR      = tar -cf
GZIP     = gzip -9f
COPY     = cp -f
COPY_FILE= $(COPY)
COPY_DIR = $(COPY) -r
INSTALL_FILE= $(COPY_FILE)
INSTALL_DIR = $(COPY_DIR)
DEL_FILE = rm -f
SYMLINK  = ln -sf
DEL_DIR  = rmdir
MOVE     = mv -f
CHK_DIR_EXISTS= test -d
MKDIR    = mkdir -p

####### Output directory

OBJECTS_DIR = build_tmp/

####### Files

HEADERS = include/paint.h \
		include/paint_common.h \
		include/paint_window.h \
		include/paint_canvas.h \
		include/paint_toolbar.h \
		include/paint_tool.h \
		include/paint_pen.h \
		include/paint_eraser.h \
		include/paint_rect.h \
		include/paint_line.h \
		include/paint_slider.h \
		include/paint_capstyle.h \
		include/paint_linestyle.h \
		include/paint_linemode.h \
		include/paint_drawtype.h \
		include/paint_fillstyle.h \
		include/paint_boundarystyle.h \
		include/paint_joinstyle.h \
		include/paint_fillcolor.h
SOURCES = src/paint.cpp \
		src/paint_window.cpp \
		src/paint_window_menu_edit.cpp \
		src/paint_window_menu_file.cpp \
		src/paint_window_menu_help.cpp \
		src/paint_window_menu_view.cpp \
		src/paint_canvas.cpp \
		src/paint_toolbar.cpp \
		src/paint_canvas_history.cpp \
		src/paint_tool.cpp \
		src/paint_pen.cpp \
		src/paint_eraser.cpp \
		src/paint_rect.cpp \
		src/paint_line.cpp \
		src/paint_slider.cpp \
		src/paint_capstyle.cpp \
		src/paint_linestyle.cpp \
		src/paint_linemode.cpp \
		src/paint_drawtype.cpp \
		src/paint_fillstyle.cpp \
		src/paint_boundarystyle.cpp \
		src/paint_joinstyle.cpp \
		src/paint_fillcolor.cpp
OBJECTS = build_tmp/paint.o \
		build_tmp/paint_window.o \
		build_tmp/paint_window_menu_edit.o \
		build_tmp/paint_window_menu_file.o \
		build_tmp/paint_window_menu_help.o \
		build_tmp/paint_window_menu_view.o \
		build_tmp/paint_canvas.o \
		build_tmp/paint_toolbar.o \
		build_tmp/paint_canvas_history.o \
		build_tmp/paint_tool.o \
		build_tmp/paint_pen.o \
		build_tmp/paint_eraser.o \
		build_tmp/paint_rect.o \
		build_tmp/paint_line.o \
		build_tmp/paint_slider.o \
		build_tmp/paint_capstyle.o \
		build_tmp/paint_linestyle.o \
		build_tmp/paint_linemode.o \
		build_tmp/paint_drawtype.o \
		build_tmp/paint_fillstyle.o \
		build_tmp/paint_boundarystyle.o \
		build_tmp/paint_joinstyle.o \
		build_tmp/paint_fillcolor.o
FORMS = 
UICDECLS = 
UICIMPLS = 
SRCMOC   = build_tmp/moc_paint_window.cpp \
		build_tmp/moc_paint_canvas.cpp \
		build_tmp/moc_paint_toolbar.cpp \
		build_tmp/moc_paint_tool.cpp \
		build_tmp/moc_paint_pen.cpp \
		build_tmp/moc_paint_eraser.cpp \
		build_tmp/moc_paint_rect.cpp \
		build_tmp/moc_paint_line.cpp \
		build_tmp/moc_paint_slider.cpp \
		build_tmp/moc_paint_capstyle.cpp \
		build_tmp/moc_paint_linestyle.cpp \
		build_tmp/moc_paint_linemode.cpp \
		build_tmp/moc_paint_drawtype.cpp \
		build_tmp/moc_paint_fillstyle.cpp \
		build_tmp/moc_paint_boundarystyle.cpp \
		build_tmp/moc_paint_joinstyle.cpp \
		build_tmp/moc_paint_fillcolor.cpp
OBJMOC = build_tmp/moc_paint_window.o \
		build_tmp/moc_paint_canvas.o \
		build_tmp/moc_paint_toolbar.o \
		build_tmp/moc_paint_tool.o \
		build_tmp/moc_paint_pen.o \
		build_tmp/moc_paint_eraser.o \
		build_tmp/moc_paint_rect.o \
		build_tmp/moc_paint_line.o \
		build_tmp/moc_paint_slider.o \
		build_tmp/moc_paint_capstyle.o \
		build_tmp/moc_paint_linestyle.o \
		build_tmp/moc_paint_linemode.o \
		build_tmp/moc_paint_drawtype.o \
		build_tmp/moc_paint_fillstyle.o \
		build_tmp/moc_paint_boundarystyle.o \
		build_tmp/moc_paint_joinstyle.o \
		build_tmp/moc_paint_fillcolor.o
DIST	   = paint.pro
QMAKE_TARGET = paint
DESTDIR  = build_bin/
TARGET   = build_bin/paint

first: all
####### Implicit rules

.SUFFIXES: .c .o .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o $@ $<

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(UICDECLS) $(OBJECTS) $(OBJMOC)  
	test -d build_bin/ || mkdir -p build_bin/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJMOC) $(OBJCOMP) $(LIBS)
	cp -r resource/* build_bin

mocables: $(SRCMOC)
uicables: $(UICDECLS) $(UICIMPLS)

$(MOC): 
	( cd $(QTDIR)/src/moc && $(MAKE) )

Makefile: paint.pro  /usr/lib64/qt-3.3/mkspecs/linux-g++-64/qmake.conf /usr/lib64/qt-3.3/lib/libqt-mt.prl
	$(QMAKE) -o Makefile paint.pro
qmake: 
	@$(QMAKE) -o Makefile paint.pro

dist: 
	@mkdir -p build_tmp/paint && $(COPY_FILE) --parents $(SOURCES) $(HEADERS) $(FORMS) $(DIST) build_tmp/paint/ && ( cd `dirname build_tmp/paint` && $(TAR) paint.tar paint && $(GZIP) paint.tar ) && $(MOVE) `dirname build_tmp/paint`/paint.tar.gz . && $(DEL_FILE) -r build_tmp/paint

mocclean:
	-$(DEL_FILE) $(OBJMOC)
	-$(DEL_FILE) $(SRCMOC)

uiclean:

yaccclean:
lexclean:
clean: mocclean
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) build_bin/$(TARGET) $(TARGET)


FORCE:

####### Compile

build_tmp/paint.o: src/paint.cpp include/paint_window.h \
		include/paint_common.h \
		include/paint_canvas.h \
		include/paint_toolbar.h \
		include/paint_pen.h \
		include/paint_line.h \
		include/paint_rect.h \
		include/paint_eraser.h \
		include/paint_tool.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build_tmp/paint.o src/paint.cpp

build_tmp/paint_window.o: src/paint_window.cpp include/paint_window.h \
		include/paint_canvas.h \
		include/paint_toolbar.h \
		include/paint_common.h \
		include/paint_pen.h \
		include/paint_line.h \
		include/paint_rect.h \
		include/paint_eraser.h \
		include/paint_tool.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build_tmp/paint_window.o src/paint_window.cpp

build_tmp/paint_window_menu_edit.o: src/paint_window_menu_edit.cpp include/paint_window.h \
		include/paint_common.h \
		include/paint_canvas.h \
		include/paint_toolbar.h \
		include/paint_pen.h \
		include/paint_line.h \
		include/paint_rect.h \
		include/paint_eraser.h \
		include/paint_tool.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build_tmp/paint_window_menu_edit.o src/paint_window_menu_edit.cpp

build_tmp/paint_window_menu_file.o: src/paint_window_menu_file.cpp include/paint_window.h \
		include/paint_common.h \
		include/paint_canvas.h \
		include/paint_toolbar.h \
		include/paint_pen.h \
		include/paint_line.h \
		include/paint_rect.h \
		include/paint_eraser.h \
		include/paint_tool.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build_tmp/paint_window_menu_file.o src/paint_window_menu_file.cpp

build_tmp/paint_window_menu_help.o: src/paint_window_menu_help.cpp include/paint_window.h \
		include/paint_common.h \
		include/paint_canvas.h \
		include/paint_toolbar.h \
		include/paint_pen.h \
		include/paint_line.h \
		include/paint_rect.h \
		include/paint_eraser.h \
		include/paint_tool.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build_tmp/paint_window_menu_help.o src/paint_window_menu_help.cpp

build_tmp/paint_window_menu_view.o: src/paint_window_menu_view.cpp include/paint_window.h \
		include/paint_common.h \
		include/paint_canvas.h \
		include/paint_toolbar.h \
		include/paint_pen.h \
		include/paint_line.h \
		include/paint_rect.h \
		include/paint_eraser.h \
		include/paint_tool.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build_tmp/paint_window_menu_view.o src/paint_window_menu_view.cpp

build_tmp/paint_canvas.o: src/paint_canvas.cpp include/paint_canvas.h \
		include/paint_toolbar.h \
		include/paint_pen.h \
		include/paint_line.h \
		include/paint_eraser.h \
		include/paint_rect.h \
		include/paint_common.h \
		include/paint_tool.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build_tmp/paint_canvas.o src/paint_canvas.cpp

build_tmp/paint_toolbar.o: src/paint_toolbar.cpp include/paint_toolbar.h \
		include/paint_window.h \
		include/paint_canvas.h \
		include/paint_common.h \
		include/paint_pen.h \
		include/paint_line.h \
		include/paint_rect.h \
		include/paint_eraser.h \
		include/paint_tool.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build_tmp/paint_toolbar.o src/paint_toolbar.cpp

build_tmp/paint_canvas_history.o: src/paint_canvas_history.cpp include/paint_canvas.h \
		include/paint_common.h \
		include/paint_pen.h \
		include/paint_line.h \
		include/paint_rect.h \
		include/paint_eraser.h \
		include/paint_tool.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build_tmp/paint_canvas_history.o src/paint_canvas_history.cpp

build_tmp/paint_tool.o: src/paint_tool.cpp include/paint_tool.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build_tmp/paint_tool.o src/paint_tool.cpp

build_tmp/paint_pen.o: src/paint_pen.cpp include/paint_pen.h \
		include/paint_capstyle.h \
		include/paint_slider.h \
		include/paint_common.h \
		include/paint_tool.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build_tmp/paint_pen.o src/paint_pen.cpp

build_tmp/paint_eraser.o: src/paint_eraser.cpp include/paint_eraser.h \
		include/paint_slider.h \
		include/paint_common.h \
		include/paint_tool.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build_tmp/paint_eraser.o src/paint_eraser.cpp

build_tmp/paint_rect.o: src/paint_rect.cpp include/paint_rect.h \
		include/paint_drawtype.h \
		include/paint_fillstyle.h \
		include/paint_boundarystyle.h \
		include/paint_joinstyle.h \
		include/paint_fillcolor.h \
		include/paint_slider.h \
		include/paint_common.h \
		include/paint_tool.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build_tmp/paint_rect.o src/paint_rect.cpp

build_tmp/paint_line.o: src/paint_line.cpp include/paint_line.h \
		include/paint_linestyle.h \
		include/paint_capstyle.h \
		include/paint_linemode.h \
		include/paint_slider.h \
		include/paint_common.h \
		include/paint_tool.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build_tmp/paint_line.o src/paint_line.cpp

build_tmp/paint_slider.o: src/paint_slider.cpp include/paint_slider.h \
		include/paint_common.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build_tmp/paint_slider.o src/paint_slider.cpp

build_tmp/paint_capstyle.o: src/paint_capstyle.cpp include/paint_capstyle.h \
		include/paint_common.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build_tmp/paint_capstyle.o src/paint_capstyle.cpp

build_tmp/paint_linestyle.o: src/paint_linestyle.cpp include/paint_linestyle.h \
		include/paint_common.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build_tmp/paint_linestyle.o src/paint_linestyle.cpp

build_tmp/paint_linemode.o: src/paint_linemode.cpp include/paint_linemode.h \
		include/paint_common.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build_tmp/paint_linemode.o src/paint_linemode.cpp

build_tmp/paint_drawtype.o: src/paint_drawtype.cpp include/paint_drawtype.h \
		include/paint_common.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build_tmp/paint_drawtype.o src/paint_drawtype.cpp

build_tmp/paint_fillstyle.o: src/paint_fillstyle.cpp include/paint_fillstyle.h \
		include/paint_common.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build_tmp/paint_fillstyle.o src/paint_fillstyle.cpp

build_tmp/paint_boundarystyle.o: src/paint_boundarystyle.cpp include/paint_boundarystyle.h \
		include/paint_common.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build_tmp/paint_boundarystyle.o src/paint_boundarystyle.cpp

build_tmp/paint_joinstyle.o: src/paint_joinstyle.cpp include/paint_joinstyle.h \
		include/paint_common.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build_tmp/paint_joinstyle.o src/paint_joinstyle.cpp

build_tmp/paint_fillcolor.o: src/paint_fillcolor.cpp include/paint_fillcolor.h \
		include/paint_common.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build_tmp/paint_fillcolor.o src/paint_fillcolor.cpp

build_tmp/moc_paint_window.o: build_tmp/moc_paint_window.cpp  include/paint_window.h include/paint_common.h \
		include/paint_canvas.h \
		include/paint_toolbar.h \
		include/paint_pen.h \
		include/paint_line.h \
		include/paint_rect.h \
		include/paint_eraser.h \
		include/paint_tool.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build_tmp/moc_paint_window.o build_tmp/moc_paint_window.cpp

build_tmp/moc_paint_canvas.o: build_tmp/moc_paint_canvas.cpp  include/paint_canvas.h include/paint_common.h \
		include/paint_pen.h \
		include/paint_line.h \
		include/paint_rect.h \
		include/paint_eraser.h \
		include/paint_tool.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build_tmp/moc_paint_canvas.o build_tmp/moc_paint_canvas.cpp

build_tmp/moc_paint_toolbar.o: build_tmp/moc_paint_toolbar.cpp  include/paint_toolbar.h include/paint_common.h \
		include/paint_canvas.h \
		include/paint_pen.h \
		include/paint_line.h \
		include/paint_rect.h \
		include/paint_eraser.h \
		include/paint_tool.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build_tmp/moc_paint_toolbar.o build_tmp/moc_paint_toolbar.cpp

build_tmp/moc_paint_tool.o: build_tmp/moc_paint_tool.cpp  include/paint_tool.h 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build_tmp/moc_paint_tool.o build_tmp/moc_paint_tool.cpp

build_tmp/moc_paint_pen.o: build_tmp/moc_paint_pen.cpp  include/paint_pen.h include/paint_common.h \
		include/paint_tool.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build_tmp/moc_paint_pen.o build_tmp/moc_paint_pen.cpp

build_tmp/moc_paint_eraser.o: build_tmp/moc_paint_eraser.cpp  include/paint_eraser.h include/paint_common.h \
		include/paint_tool.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build_tmp/moc_paint_eraser.o build_tmp/moc_paint_eraser.cpp

build_tmp/moc_paint_rect.o: build_tmp/moc_paint_rect.cpp  include/paint_rect.h include/paint_common.h \
		include/paint_tool.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build_tmp/moc_paint_rect.o build_tmp/moc_paint_rect.cpp

build_tmp/moc_paint_line.o: build_tmp/moc_paint_line.cpp  include/paint_line.h include/paint_common.h \
		include/paint_tool.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build_tmp/moc_paint_line.o build_tmp/moc_paint_line.cpp

build_tmp/moc_paint_slider.o: build_tmp/moc_paint_slider.cpp  include/paint_slider.h include/paint_common.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build_tmp/moc_paint_slider.o build_tmp/moc_paint_slider.cpp

build_tmp/moc_paint_capstyle.o: build_tmp/moc_paint_capstyle.cpp  include/paint_capstyle.h include/paint_common.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build_tmp/moc_paint_capstyle.o build_tmp/moc_paint_capstyle.cpp

build_tmp/moc_paint_linestyle.o: build_tmp/moc_paint_linestyle.cpp  include/paint_linestyle.h include/paint_common.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build_tmp/moc_paint_linestyle.o build_tmp/moc_paint_linestyle.cpp

build_tmp/moc_paint_linemode.o: build_tmp/moc_paint_linemode.cpp  include/paint_linemode.h include/paint_common.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build_tmp/moc_paint_linemode.o build_tmp/moc_paint_linemode.cpp

build_tmp/moc_paint_drawtype.o: build_tmp/moc_paint_drawtype.cpp  include/paint_drawtype.h include/paint_common.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build_tmp/moc_paint_drawtype.o build_tmp/moc_paint_drawtype.cpp

build_tmp/moc_paint_fillstyle.o: build_tmp/moc_paint_fillstyle.cpp  include/paint_fillstyle.h include/paint_common.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build_tmp/moc_paint_fillstyle.o build_tmp/moc_paint_fillstyle.cpp

build_tmp/moc_paint_boundarystyle.o: build_tmp/moc_paint_boundarystyle.cpp  include/paint_boundarystyle.h include/paint_common.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build_tmp/moc_paint_boundarystyle.o build_tmp/moc_paint_boundarystyle.cpp

build_tmp/moc_paint_joinstyle.o: build_tmp/moc_paint_joinstyle.cpp  include/paint_joinstyle.h include/paint_common.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build_tmp/moc_paint_joinstyle.o build_tmp/moc_paint_joinstyle.cpp

build_tmp/moc_paint_fillcolor.o: build_tmp/moc_paint_fillcolor.cpp  include/paint_fillcolor.h include/paint_common.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build_tmp/moc_paint_fillcolor.o build_tmp/moc_paint_fillcolor.cpp

build_tmp/moc_paint_window.cpp: $(MOC) include/paint_window.h
	$(MOC) include/paint_window.h -o build_tmp/moc_paint_window.cpp

build_tmp/moc_paint_canvas.cpp: $(MOC) include/paint_canvas.h
	$(MOC) include/paint_canvas.h -o build_tmp/moc_paint_canvas.cpp

build_tmp/moc_paint_toolbar.cpp: $(MOC) include/paint_toolbar.h
	$(MOC) include/paint_toolbar.h -o build_tmp/moc_paint_toolbar.cpp

build_tmp/moc_paint_tool.cpp: $(MOC) include/paint_tool.h
	$(MOC) include/paint_tool.h -o build_tmp/moc_paint_tool.cpp

build_tmp/moc_paint_pen.cpp: $(MOC) include/paint_pen.h
	$(MOC) include/paint_pen.h -o build_tmp/moc_paint_pen.cpp

build_tmp/moc_paint_eraser.cpp: $(MOC) include/paint_eraser.h
	$(MOC) include/paint_eraser.h -o build_tmp/moc_paint_eraser.cpp

build_tmp/moc_paint_rect.cpp: $(MOC) include/paint_rect.h
	$(MOC) include/paint_rect.h -o build_tmp/moc_paint_rect.cpp

build_tmp/moc_paint_line.cpp: $(MOC) include/paint_line.h
	$(MOC) include/paint_line.h -o build_tmp/moc_paint_line.cpp

build_tmp/moc_paint_slider.cpp: $(MOC) include/paint_slider.h
	$(MOC) include/paint_slider.h -o build_tmp/moc_paint_slider.cpp

build_tmp/moc_paint_capstyle.cpp: $(MOC) include/paint_capstyle.h
	$(MOC) include/paint_capstyle.h -o build_tmp/moc_paint_capstyle.cpp

build_tmp/moc_paint_linestyle.cpp: $(MOC) include/paint_linestyle.h
	$(MOC) include/paint_linestyle.h -o build_tmp/moc_paint_linestyle.cpp

build_tmp/moc_paint_linemode.cpp: $(MOC) include/paint_linemode.h
	$(MOC) include/paint_linemode.h -o build_tmp/moc_paint_linemode.cpp

build_tmp/moc_paint_drawtype.cpp: $(MOC) include/paint_drawtype.h
	$(MOC) include/paint_drawtype.h -o build_tmp/moc_paint_drawtype.cpp

build_tmp/moc_paint_fillstyle.cpp: $(MOC) include/paint_fillstyle.h
	$(MOC) include/paint_fillstyle.h -o build_tmp/moc_paint_fillstyle.cpp

build_tmp/moc_paint_boundarystyle.cpp: $(MOC) include/paint_boundarystyle.h
	$(MOC) include/paint_boundarystyle.h -o build_tmp/moc_paint_boundarystyle.cpp

build_tmp/moc_paint_joinstyle.cpp: $(MOC) include/paint_joinstyle.h
	$(MOC) include/paint_joinstyle.h -o build_tmp/moc_paint_joinstyle.cpp

build_tmp/moc_paint_fillcolor.cpp: $(MOC) include/paint_fillcolor.h
	$(MOC) include/paint_fillcolor.h -o build_tmp/moc_paint_fillcolor.cpp

####### Install

install:  

uninstall:  

